### ISSUE TITLE
When mentionList is updated, the pop up is shown automatically

### ISSUE THREAD

**Issue by vishnusbabu** [dmacfarlane/angular-mentions#80]
When the mentionList is updated with a new row, the pop up is automatically shown which is not hidden even on a click inside or outside.

**Comment by ujjawalhub** [comment]
Hey @vishnusbabu did you find any solution for this... cause I'm facing same issue while handling two mentionList.

**Comment by dmacfarlane** [comment]
Can you provide an example, with steps to reproduce the issue?

https://stackblitz.com/edit/angular-mentions

**Comment by dmacfarlane** [comment]
Fix committed to master for this issue.

**Comment by dil-aajmera** [comment]
this issue still exists, menu opening stays open even after we switch to different tab just because list items are getting updated
